name: Sync Kaggle → GitHub

on:
  schedule:
    - cron: "0 * * * *" # chạy mỗi giờ (UTC)
  workflow_dispatch: # cho phép chạy thủ công

permissions:
  contents: write

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Configure Kaggle API
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json
          echo "✅ Kaggle credentials configured"

      - name: Download Kaggle Notebook
        run: |
          mkdir -p kaggle_notebook
          kaggle kernels pull maihopeltonen/nursery-dataset-draft -p ./kaggle_notebook --force
          echo "✅ Notebook downloaded"

      - name: Commit & Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add kaggle_notebook/
          git commit -m "Auto-sync from Kaggle" || echo "No changes to commit"
          git pull --rebase
          git push
          echo "✅ Sync complete"
